# Generated by Django 3.2.5 on 2021-08-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='datecomltete',
        ),
        migrations.AddField(
            model_name='todo',
            name='datecomplete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
