# Generated by Django 3.2.5 on 2021-08-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210819_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecomplete',
            new_name='date_complete',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='date_created',
        ),
    ]
